### ISSUE TITLE
RemoveTrackingObservableCollection not thread safe

### ISSUE THREAD

**Issue by TheSylence** [grollmus/BuildNotifications#119]
BusyIndicator crashes sometimes

**Comment by BerndNK** [comment]
Its okay that the collection itself is not thread safe, as it is not intended to be used over multiple threads. (Locking the internal list, would cause huge overhead)

However the real issue of this bug, is the BusyIndicator which would sometimes hickup and crash, due to the ObservableCollection thread modifying itself while the BusyIndicator thread is also reading it.
